apiVersion: v1
kind: Service
metadata:
  name: notes-app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
  type: {{ .Values.service.type }}
